# Copyright (c) 2024-2025 Six After, Inc
#
# This source code is licensed under the Apache 2.0 License found in the
# LICENSE file in the root directory of this source tree.

# Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - name: "Preamble"
        run: |
          echo github ref $GITHUB_REF
          echo workflow $GITHUB_WORKFLOW
          echo home $HOME
          echo event name $GITHUB_EVENT_NAME
          echo workspace $GITHUB_WORKSPACE

          df -h

          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common ca-certificates gnupg-agent curl build-essential make

      # Ref: https://github.com/actions/checkout
      - name: "Checkout Source"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Ref: https://github.com/actions/setup-go
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          check-latest: true
          cache: false
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: "Compute Release Flags"
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV

      - name: Get Commit Hash
        id: get_commit
        run: |
          echo "X_BUILD_COMMIT=$(git rev-parse HEAD 2> /dev/null || echo 'unknown')" >> $GITHUB_ENV

      # Ref: https://github.com/sigstore/cosign-installer
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.10.0

      # Ref: https://github.com/anchore/sbom-action
      - name: Generate SBOM via Syft
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: sbom.spdx.json

      # Ref: https://github.com/goreleaser/goreleaser-action
      - name: "Release"
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          X_BUILD_COMMIT: ${{ env.X_BUILD_COMMIT }}
          X_GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
          COSIGN_PASSWORD: '${{ secrets.NANOID_CLI_COSIGN_PASSWORD }}'
          COSIGN_PRIVATE_KEY: '${{ secrets.NANOID_CLI_COSIGN_PRIVATE_KEY }}'
          COSIGN_PUBLIC_KEY: '${{ secrets.NANOID_CLI_COSIGN_PUBLIC_KEY }}'
          SIXAFTER_MACOS_NOTARY_ISSUER_ID: '${{ secrets.SIXAFTER_MACOS_NOTARY_ISSUER_ID }}'
          SIXAFTER_MACOS_NOTARY_KEY: '${{ secrets.SIXAFTER_MACOS_NOTARY_KEY }}'
          SIXAFTER_MACOS_NOTARY_KEY_ID: '${{ secrets.SIXAFTER_MACOS_NOTARY_KEY_ID }}'
          SIXAFTER_MACOS_SIGN_P12: '${{ secrets.SIXAFTER_MACOS_SIGN_P12 }}'
          SIXAFTER_MACOS_SIGN_PASSWORD: '${{ secrets.SIXAFTER_MACOS_SIGN_PASSWORD }}'
